"""
Render Manager TUI
Consolidates image processing and manifest assembly into a single tool.
"""

import calendar
import json
import logging
import os
import sys
from pathlib import Path
import cv2

try:
    import tomllib
except ImportError:
    # Fallback for Python < 3.11 if needed, but we are on 3.14
    import itomllib as tomllib

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(levelname)s: %(message)s'
)
logger = logging.getLogger(__name__)

# Constants
UTILS_DIR = Path(__file__).parent
PROJECT_ROOT = UTILS_DIR.parent
DEFAULT_CONFIG_FILE = UTILS_DIR / "render_config.toml"

DEFAULT_PATHS = {
    "source_renders_dir": str(UTILS_DIR / "renders"),
    "output_web_images_dir": str(PROJECT_ROOT / "public/images/renders"),
    "output_individual_json_dir": str(UTILS_DIR / "lib"),
    "src_json_dir": str(PROJECT_ROOT / "src/jsondata"),
    "debug_web_images_dir": str(UTILS_DIR / "debug_renders"),
    "debug_individual_json_dir": str(UTILS_DIR / "debug_lib"),
    "debug_manifest_output": str(UTILS_DIR / "debug_render-map.json"),
}

PATH_DESCRIPTIONS = {
    "source_renders_dir": "Directory containing the source PNG renders, organized by category.",
    "output_web_images_dir": "Root directory where processed web-optimized images (JPEG) will be stored.",
    "output_individual_json_dir": "Directory where individual image manifest JSON files are stored.",
    "src_json_dir": "Directory where the final consolidated render-map.json will be saved.",
    "debug_web_images_dir": "Output directory for web images when running in Debug Mode.",
    "debug_individual_json_dir": "Output directory for individual manifests when running in Debug Mode.",
    "debug_manifest_output": "Path to the consolidated manifest file when running in Debug Mode.",
}

MANIFEST_OUTPUT_NAME = "render-map.json"
CATEGORIES = ["env", "char", "char-env"]
MONTH_TO_NUM = {name: i for i, name in enumerate(calendar.month_name) if name}


class ConfigManager:
    def __init__(self, config_file=DEFAULT_CONFIG_FILE):
        self.config_file = config_file
        self.paths = DEFAULT_PATHS.copy()
        self.load_config()

    def load_config(self):
        if self.config_file.exists():
            try:
                with open(self.config_file, 'rb') as f:
                    loaded_paths = tomllib.load(f)
                    self.paths.update(loaded_paths)
            except Exception as e:
                logger.error(f"Failed to load config: {e}")

    def save_config(self):
        try:
            with open(self.config_file, 'w') as f:
                f.write("# Render Manager Configuration\n")
                f.write("# This file is automatically generated. You can manually edit the paths below.\n\n")
                for key, value in self.paths.items():
                    description = PATH_DESCRIPTIONS.get(key, "")
                    if description:
                        f.write(f"# {description}\n")
                    f.write(f'{key} = "{value}"\n\n')
            logger.info(f"Configuration saved to {self.config_file}")
        except Exception as e:
            logger.error(f"Failed to save config: {e}")

    def get_path(self, key: str) -> Path:
        return Path(self.paths.get(key, DEFAULT_PATHS[key]))

    def configure_menu(self):
        while True:
            clear_screen()
            print("========================================")
            print("        DIRECTORY CONFIGURATION         ")
            print("========================================")
            keys = list(self.paths.keys())
            for idx, key in enumerate(keys, 1):
                print(f" {idx}. {key.replace('_', ' ').title()}")
                print(f"    Current: {self.paths[idx-1 if idx-1 < 0 else idx-1] if isinstance(idx, str) else self.paths[key]}")

            print("----------------------------------------")
            print(" r. Reset to Defaults")
            print(" b. Back to Main Menu")
            print("----------------------------------------")

            choice = input("Select a directory to change (1-7, r, b): ").strip().lower()

            if choice == 'b':
                break
            elif choice == 'r':
                self.paths = DEFAULT_PATHS.copy()
                self.save_config()
                input("\nPaths reset to defaults. Press Enter...")
            elif choice.isdigit() and 1 <= int(choice) <= len(keys):
                key = keys[int(choice) - 1]
                print(f"\nChanging {key.replace('_', ' ').title()}")
                new_path = input(f"Enter new path (current: {self.paths[key]}): ").strip()
                if new_path:
                    self.paths[key] = new_path
                    self.save_config()
                    input("\nPath updated. Press Enter...")
            else:
                print("Invalid choice.")
                input("\nPress Enter to continue...")


class RenderProcessor:
    def __init__(self, config: ConfigManager, debug=False):
        self.config = config
        self.debug = debug
        self.web_dir = config.get_path("debug_web_images_dir") if debug else config.get_path("output_web_images_dir")
        self.json_dir = config.get_path("debug_individual_json_dir") if debug else config.get_path("output_individual_json_dir")
        self.source_dir = config.get_path("source_renders_dir")

    def ensure_dir(self, path: Path) -> None:
        path.mkdir(parents=True, exist_ok=True)

    def parse_date(self, raw_date: str) -> tuple[int, str]:
        year_str = "".join(filter(str.isdigit, raw_date))
        month_part = raw_date.replace(year_str, "").capitalize()
        year = int(year_str) if year_str else 0
        month_name = ""
        for i, m in enumerate(calendar.month_name):
            if m and month_part.lower() in m.lower():
                month_name = m
                break
        return year, month_name

    def process_image(self, img_path: Path) -> None:
        if img_path.suffix.lower() not in ['.png', '.jpg', '.jpeg']:
            return

        stem = img_path.stem
        parts = stem.split("-")
        if len(parts) < 2:
            logger.error(f"Filename '{img_path.name}' must follow 'Name-MonthYear' format.")
            return

        name = parts[0]
        year, month = self.parse_date(parts[1])
        
        logger.info(f"--- Processing: {name} ---")
        
        # Subdirectory logic
        # Ensure target directory is unique by including parent folder name if it's not the category
        name_slug = name.replace(" ", "-").lower()
        rel_parent = img_path.parent.relative_to(self.source_dir)
        target_dir = self.web_dir / rel_parent / name_slug
        self.ensure_dir(target_dir)

        sizes_paths = []
        for width, label in [(1920, 'lg'), (1600, 'md'), (1200, 'sm')]:
            suffix = f"-{label}.jpg"
            file_name = name.replace(" ", "_")
            target_path = target_dir / f"{file_name}{suffix}"
            
            if not target_path.exists():
                img = cv2.imread(str(img_path))
                if img is None:
                    logger.error(f"Could not read {img_path}")
                    return
                h, w = img.shape[:2]
                if w > width:
                    new_h = int(width * h / w)
                    img = cv2.resize(img, (width, new_h), interpolation=cv2.INTER_AREA)
                cv2.imwrite(str(target_path), img, [cv2.IMWRITE_JPEG_QUALITY, 80])
                logger.info(f"Created {target_path.name}")
            else:
                logger.info(f"Skipping {target_path.name} (exists)")
            sizes_paths.append(target_path.name)

        # JSON Metadata
        # Edgecase: same name but different date. Folder name usually includes the date.
        json_name = name.replace(' ', '_')
        if img_path.parent.name != parts[1]:
            # If the folder name is not just the month/year (e.g. "Sakura-2024"), use it to differentiate
            json_name = f"{json_name}_{img_path.parent.name.replace(' ', '_')}"
        else:
            # Fallback to name_month_year if they are likely to collide
            json_name = f"{json_name}_{month}_{year}"
            
        json_path = self.json_dir / img_path.parent.relative_to(self.source_dir) / f"{json_name}.json"
        self.ensure_dir(json_path.parent)
        
        manifest_data = {
            "name": name,
            "year": year,
            "month": month,
            "description": "",
            "folder": img_path.parent.name,
            "sizes": sizes_paths
        }

        if json_path.exists():
            try:
                with open(json_path, 'r') as f:
                    old_data = json.load(f)
                if old_data.get("description"):
                    manifest_data["description"] = old_data["description"]
            except Exception:
                pass

        with open(json_path, 'w') as f:
            json.dump(manifest_data, f, indent=4)
        logger.info(f"Saved Manifest: {json_path.name}")

    def process_category(self, category: str) -> None:
        cat_dir = self.source_dir / category
        if not cat_dir.is_dir():
            logger.warning(f"Category directory not found: {cat_dir}")
            return
        for img_path in cat_dir.rglob("*"):
            if img_path.is_file():
                self.process_image(img_path)

    def process_all(self) -> None:
        for cat in CATEGORIES:
            self.process_category(cat)


class ManifestAssembler:
    def __init__(self, config: ConfigManager, debug=False):
        self.config = config
        self.debug = debug
        self.lib_path = config.get_path("debug_individual_json_dir") if debug else config.get_path("output_individual_json_dir")
        self.output_file = config.get_path("debug_manifest_output") if debug else config.get_path("src_json_dir") / MANIFEST_OUTPUT_NAME

    def get_image_date_key(self, img: dict) -> tuple[int, int]:
        year = img.get("year", 0)
        month_val = img.get("month", "")
        month_num = month_val if isinstance(month_val, int) else MONTH_TO_NUM.get(month_val, 0)
        return year, month_num

    def load_category_images(self, category: str) -> list[dict]:
        cat_dir = self.lib_path / category
        if not cat_dir.is_dir():
            return []
        images = []
        for json_file in cat_dir.rglob("*.json"):
            try:
                with open(json_file, 'r') as f:
                    images.append(json.load(f))
            except Exception as e:
                logger.error(f"Error reading {json_file}: {e}")
        images.sort(key=self.get_image_date_key, reverse=True)
        return images

    def assemble(self) -> None:
        logger.info(f"Assembling manifest from: {self.lib_path}")
        combined_manifest = [
            {
                "label": "Characters in Environments",
                "path": f"/{CATEGORIES[2]}/",
                "images": self.load_category_images(CATEGORIES[2]),
            },
            {
                "label": "Environments",
                "path": f"/{CATEGORIES[0]}/",
                "images": self.load_category_images(CATEGORIES[0]),
            },
            {
                "label": "Character Portraits",
                "path": f"/{CATEGORIES[1]}/",
                "images": self.load_category_images(CATEGORIES[1]),
            },
        ]
        self.output_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self.output_file, 'w') as f:
            json.dump(combined_manifest, f, indent=4)
        logger.info(f"Successfully assembled manifest at {self.output_file}")


def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')


def main_menu():
    config = ConfigManager()
    debug_mode = False
    while True:
        clear_screen()
        print("========================================")
        print("          RENDER MANAGER TUI            ")
        print("========================================")
        print(f" Status: {'[DEBUG MODE]' if debug_mode else '[PRODUCTION MODE]'}")
        print("----------------------------------------")
        print(" 1. Process New Renders (Images -> JSON)")
        print(" 2. Assemble Complete Manifest (JSON -> render-map.json)")
        print(" 3. Run Full Pipeline (1 then 2)")
        print(" 4. Toggle Debug/Production Mode")
        print(" 5. Configure Directories")
        print(" 6. Exit")
        print("----------------------------------------")
        
        choice = input("Select an option (1-6): ").strip()

        if choice == '1':
            RenderProcessor(config, debug=debug_mode).process_all()
            input("\nPress Enter to continue...")
        elif choice == '2':
            ManifestAssembler(config, debug=debug_mode).assemble()
            input("\nPress Enter to continue...")
        elif choice == '3':
            RenderProcessor(config, debug=debug_mode).process_all()
            ManifestAssembler(config, debug=debug_mode).assemble()
            input("\n\nPipeline complete. Press Enter to continue...")
        elif choice == '4':
            debug_mode = not debug_mode
            logger.info(f"Debug mode set to: {debug_mode}")
        elif choice == '5':
            config.configure_menu()
        elif choice == '6':
            print("Exiting...")
            break
        else:
            print("Invalid choice.")
            input("\nPress Enter to continue...")


if __name__ == "__main__":
    try:
        main_menu()
    except KeyboardInterrupt:
        print("\nExiting...")
        sys.exit(0)
